apiVersion: apps/v1
kind: Deployment
metadata:
  #annotations:
    #kubernetes.io/change-cause: "Change port to 110"
  name: deployment-test
  labels:
    app: front
spec:
  #revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        #ports:
          #- containerPort: 110
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      # puerto en el que el servicio va a estar escuchando
      port: 8080
      # a que puerto dentro del contenedor o del pod voy a consumir
      # puerto donde corre nginx
      targetPort: 80
